<!doctype html>
<html lang="id">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?= esc($title) ?></title>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700&family=Playfair+Display:wght@600;700&display=swap" rel="stylesheet">
    <style>
        *{box-sizing:border-box}body{margin:0;background:#fcf9f4;color:#261e1a;font:14px 'Plus Jakarta Sans',sans-serif}.wrap{max-width:1200px;margin:auto;padding:30px 20px}.top,.actions,.filters{display:flex;align-items:center;justify-content:space-between;gap:12px}.top{margin-bottom:22px}.title{font:700 30px 'Playfair Display',serif;margin:8px 0}.muted{color:#71655e}.card{background:#ffffffdc;border:1px solid #eadfcf;border-radius:20px;padding:22px;margin-bottom:18px}.filters{justify-content:flex-start;flex-wrap:wrap}.filters label{display:grid;gap:5px;color:#71655e;font-size:12px}input{font:inherit;border:1px solid #ded2c4;border-radius:10px;padding:10px;background:#fff}.button{display:inline-block;border:0;border-radius:999px;background:#c85a32;color:white;padding:11px 17px;text-decoration:none;font:600 13px 'Plus Jakarta Sans',sans-serif;cursor:pointer}.button.outline{background:white;color:#57423b;border:1px solid #eadfcf}.stats{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.stat{background:#fcf9f4;border-radius:14px;padding:16px}.stat strong{display:block;font-size:22px;margin-top:6px}table{border-collapse:collapse;width:100%}th{text-align:left;text-transform:uppercase;font-size:11px;letter-spacing:.05em;color:#71655e;padding:12px;border-bottom:1px solid #eadfcf}td{padding:13px 12px;border-bottom:1px solid #f0e9df}.right{text-align:right}.empty{text-align:center;padding:30px;color:#71655e}@media(max-width:650px){.wrap{padding:18px 12px}.top{align-items:flex-start}.card{padding:15px;overflow:auto}.stats{grid-template-columns:1fr}.filters{align-items:stretch}.filters label{flex:1;min-width:130px}}
    </style>
</head>
<body>
<main class="wrap">
    <header class="top"><div><div class="muted">Griya Pot Bunga / Admin</div><h1 class="title">Laporan Pesanan</h1><div class="muted">Pilih rentang tanggal untuk memfilter pesanan dan ekspor laporan.</div></div><div class="actions"><a class="button outline" href="<?= base_url('/dashboard') ?>">Dashboard</a><a class="button outline" href="<?= base_url('/admin/kelola-produk') ?>">Kelola Produk</a></div></header>
    <section class="card"><form class="filters" method="get" action="<?= base_url('/admin/laporan') ?>"><label>Dari<input type="date" name="start_date" value="<?= esc($startDate) ?>" required></label><label>Sampai<input type="date" name="end_date" value="<?= esc($endDate) ?>" required></label><button class="button" type="submit">Terapkan filter</button><a class="button outline" href="<?= base_url('/admin/laporan') ?>">Reset</a></form></section>
    <section class="card stats"><div class="stat"><span class="muted">Rentang tanggal</span><strong><?= esc(date('d M Y', strtotime($startDate))) ?> – <?= esc(date('d M Y', strtotime($endDate))) ?></strong></div><div class="stat"><span class="muted">Jumlah pesanan</span><strong><?= esc($totalTransactions) ?></strong></div><div class="stat"><span class="muted">Pendapatan (di luar pesanan dibatalkan)</span><strong>Rp <?= number_format($totalRevenue, 0, ',', '.') ?></strong></div></section>
    <section class="card"><div class="top"><div><h2>Daftar Pesanan</h2><div class="muted">Data checkout pada periode terpilih.</div></div><div class="actions"><a class="button outline" href="<?= base_url('/admin/laporan/export-pdf?' . http_build_query(['start_date' => $startDate, 'end_date' => $endDate])) ?>">Export PDF</a><a class="button" href="<?= base_url('/admin/laporan/export?' . http_build_query(['start_date' => $startDate, 'end_date' => $endDate])) ?>">Export CSV</a></div></div>
        <?php if ($transactions): ?><table><thead><tr><th>Nomor pesanan</th><th>Tanggal</th><th>Pelanggan</th><th>Status</th><th class="right">Total</th></tr></thead><tbody><?php foreach ($transactions as $transaction): ?><tr><td><?= esc($transaction['nomor_transaksi']) ?></td><td><?= esc(date('d M Y H:i', strtotime($transaction['tanggal']))) ?></td><td><?= esc($transaction['nama_pelanggan'] ?? 'Pelanggan') ?></td><td><?= esc($transaction['status']) ?></td><td class="right">Rp <?= number_format((float) $transaction['total_harga'], 0, ',', '.') ?></td></tr><?php endforeach; ?></tbody></table><?php else: ?><div class="empty">Tidak ada pesanan pada rentang tanggal ini.</div><?php endif; ?>
    </section>
</main>
</body>
</html>
